# Generated by Django 6.0.2 on 2026-02-11 15:46

import django.db.models.deletion
import project.constants
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('processing_state', models.IntegerField(choices=project.constants.ProcessingConstants.model_choices, default=project.constants.ProcessingConstants['PENDING'])),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.IntegerField(choices=project.constants.ResourceTypeConstants.model_choices, default=project.constants.ResourceTypeConstants['OTHER'])),
                ('title', models.CharField(max_length=36, null=True)),
                ('url', models.URLField()),
                ('processing_state', models.IntegerField(choices=project.constants.ResourceProcessingConstants.model_choices, default=project.constants.ResourceProcessingConstants['PENDING'])),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('vectorising_state', models.IntegerField(choices=project.constants.ProcessingConstants.model_choices, default=project.constants.ProcessingConstants['PENDING'])),
                ('created_on', models.DateField(auto_now=True)),
                ('completed_on', models.DateField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.resource')),
            ],
            options={
                'db_table': 'resource_chunk',
            },
        ),
    ]
