# Generated by Django 6.0.2 on 2026-02-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resourcechunks',
            name='url',
        ),
        migrations.AddField(
            model_name='resource',
            name='data',
            field=models.FileField(default='documents/', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcechunks',
            name='data',
            field=models.FileField(default='documents/', upload_to='chunks/'),
            preserve_default=False,
        ),
    ]
